
all:
  children:
    dns_servers:
      hosts:
        server1:
#dns server information:
          ansible_host: 172.16.17.3
          ansible_user: root
      vars:
        dns_zone: "thesis.local"
        dns_zone_file: "/etc/bind/db.thesis.local"
    ftp_servers:
      hosts:
        server2:
#ftp server information:
          ansible_host: 172.16.17.4
          ansible_user: root
          ftp_users:
            - name: "ftpuser1"
              password: "ftppass"
              home_dir: "/home/ftpuser1"
            - name: "ftpuser2"
              password: "ftppass"
              home_dir: "/home/ftpuser2"
