---
- name: Create FTP users on FTP servers
  hosts: ftp_servers
  become: true
  tasks:
    - name: Create FTP users
      user:
        name: "{{ item.name }}"
        password: "{{ item.password | password_hash('sha512') }}"
        home: "{{ item.home_dir }}"
        state: present
      loop: "{{ ftp_users }}"
